-- Search Engine Schema v0.1.0
-- Author: Nathan M
CREATE TABLE `Resource` (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	full_domain VARCHAR(253) NOT NULL UNIQUE,
    status ENUM('DISCOVERED', 'CRAWLED'),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `ResourceRoute` (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	resource_id INTEGER NOT NULL,
	route_path VARCHAR(2000) NOT NULL,
	title VARCHAR(125) NOT NULL,
	description VARCHAR(175) DEFAULT NULL,
	visit_count INTEGER NOT NULL DEFAULT 0,
    last_crawled TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (`resource_id`) REFERENCES `Resource`(`id`) ON DELETE CASCADE
);

CREATE TABLE ResourceRouteError (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	resource_route_id INTEGER NOT NULL UNIQUE,
	status_code SMALLINT NOT NULL,
	grace_period TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (`resource_route_id`) REFERENCES `ResourceRoute`(`id`) ON DELETE CASCADE
);

CREATE TABLE `ResourceReference` (
	resource_referenced_id INTEGER NOT NULL,
	resource_referencer_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (`resource_referenced_id`) REFERENCES `Resource`(`id`) ON DELETE CASCADE,
	FOREIGN KEY (`resource_referencer_id`) REFERENCES `Resource`(`id`) ON DELETE CASCADE,
	PRIMARY KEY (`resource_referenced_id`, `resource_referencer_id`)
);
